name: "Run Tests"

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'templates/**'
      - 'config/**'
      - 'composer.lock'
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

env:
  APP_ENV: test

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - php: '8.1'
            driver: 'SQLITE'
            redis: 6
            postgres: 16
            mysql: '8.4'
            symfony: '6.4.*'
          - php: '8.2'
            driver: 'PGSQL'
            redis: 6
            postgres: 16
            mysql: '8.4'
            symfony: '6.4.*'
          - php: '8.3'
            driver: 'MYSQL'
            redis: 6
            postgres: 16
            mysql: '8.4'
            symfony: '6.4.*'
          - php: '8.4'
            driver: 'SQLITE'
            redis: 7
            postgres: 16
            mysql: '8.4'
            symfony: '7.2.*'
            composer_flags: '--ignore-platform-reqs'
    name: PHP ${{ matrix.php }} ${{ matrix.driver }} SF ${{ matrix.symfony }}
    runs-on: ubuntu-22.04

    services:
      redis:
        image: redis:${{ matrix.redis }}
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      postgres:
        image: postgres:${{ matrix.postgres }}
        env:
          POSTGRES_PASSWORD: '123456'
          POSTGRES_DB: packeton
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mysql:
        image: mysql:${{ matrix.mysql }}
        env:
          MYSQL_ROOT_PASSWORD: '123456'
          MYSQL_DATABASE: packeton
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h 127.0.0.1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          extensions: "curl, pdo, pdo_sqlite, pdo_mysql, pdo_pgsql, sqlite, zip, redis"
          php-version: ${{ matrix.php }}
          tools: composer

      - name: "Install dependencies"
        run: |
          set -x
          echo $DATABASE_URL
          if [[ "${{ matrix.symfony }}" != "6.4.*" ]]; then
            export SYMFONY_REQUIRE="${{ matrix.symfony }}"
            composer update --ansi --no-interaction ${{ matrix.composer_flags }}
          else
            composer install --ansi --no-interaction ${{ matrix.composer_flags }}
          fi
      - name: "Prepare Postgres"
        if: ${{ matrix.driver=='PGSQL' }}
        run: |
          set -x
          echo 'DATABASE_URL="postgresql://postgres:123456@127.0.0.1/packeton?serverVersion=14.0&charset=utf8"' >> .env.test;
          bin/console doctrine:schema:update --force --complete
          
          gunzip -c tests/dump/test.db.gz > tests/dump/test.db
          php tests/import_db.php sqlite:////${PWD}/tests/dump/test.db postgresql://postgres:123456@127.0.0.1/packeton

      - name: "Prepare MySql"
        if: ${{ matrix.driver=='MYSQL' }}
        run: |
          set -x
          echo 'DATABASE_URL="mysql://root:123456@127.0.0.1/packeton?serverVersion=8.0&charset=utf8mb4"' >> .env.test;
          bin/console doctrine:schema:update --force --complete
  
          gunzip -c tests/dump/test.db.gz > tests/dump/test.db
          php tests/import_db.php sqlite:////${PWD}/tests/dump/test.db mysql://root:123456@127.0.0.1:3306/packeton

      - name: "Run tests"
        run: "composer tests"
